{
 "title": "HORNETs Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "LSM/LSMI",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "iota_info_latest_solid_milestone_index{instance=\"$instance\"}",
     "legendFormat": "LSMI"
    },
    {
     "expr": "iota_info_latest_milestone_index{instance=\"$instance\"}",
     "legendFormat": "LSM"
    }
   ]
  },
  {
   "title": "Bundles Validated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "iota_server_validated_bundles{instance=\"$instance\"}",
     "legendFormat": "Bundles Validates"
    }
   ]
  },
  {
   "title": "Seen Spent Addresses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "iota_server_seen_spent_addresses{instance=\"$instance\"}",
     "legendFormat": "Seen Spent Addresses"
    }
   ]
  },
  {
   "title": "Peers Connected",
   "type": "graph",
   "description": "Number of currently connected peers",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(iota_peers_connected{instance=\"$instance\"} == 1)"
    }
   ]
  },
  {
   "title": "General Stats",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "iota_server_sent_transactions{instance=\"$instance\"}",
     "legendFormat": "Sent Tx"
    },
    {
     "expr": "iota_server_new_transactions{instance=\"$instance\"}",
     "legendFormat": "New Tx"
    },
    {
     "expr": "iota_server_sent_spam_transactions{instance=\"$instance\"}",
     "legendFormat": "Sent Spam Tx "
    },
    {
     "expr": "iota_server_invalid_transactions{instance=\"$instance\"}",
     "legendFormat": "Invalid Tx"
    },
    {
     "expr": "iota_server_sent_transaction_requests{instance=\"$instance\"}",
     "legendFormat": "Sent Tx Req"
    },
    {
     "expr": "iota_server_received_transaction_requests{instance=\"$instance\"}",
     "legendFormat": "Received Tx Req"
    },
    {
     "expr": "iota_server_stale_transactions{instance=\"$instance\"}",
     "legendFormat": "Stale Tx"
    },
    {
     "expr": "iota_server_sent_heartbeats{instance=\"$instance\"}",
     "legendFormat": "Sent Heartbeats"
    },
    {
     "expr": "iota_server_received_heartbeats{instance=\"$instance\"}",
     "legendFormat": "Received Heartbeats"
    }
   ]
  },
  {
   "title": "Request Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iota_info_transactions_to_request{instance=\"$instance\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Confirmation Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(rate(iota_server_confirmed_transactions{instance=\"$instance\"}[10m])/rate(iota_server_new_transactions{instance=\"$instance\"}[10m]))*100",
     "legendFormat": "Conf. Rate"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "TPS/CTPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(iota_server_new_transactions{instance=\"$instance\"}[1m])",
     "legendFormat": "TPS"
    },
    {
     "expr": "irate(iota_server_confirmed_transactions{instance=\"$instance\"}[1m])",
     "legendFormat": "CTPS"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "iota_data_sizes_bytes{instance=\"$instance\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"$instance\"}[1m])*100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"$instance\"} + go_memstats_heap_idle_bytes{instance=\"$instance\"} - go_memstats_heap_released_bytes{instance=\"$instance\"} + go_memstats_mspan_inuse_bytes{instance=\"$instance\"} + go_memstats_mcache_inuse_bytes{instance=\"$instance\"} + go_memstats_stack_inuse_bytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "avg_over_time(go_memstats_heap_inuse_bytes{instance=\"$instance\"}[1m])",
     "legendFormat": "Heap In-Use"
    },
    {
     "expr": "avg_over_time(go_memstats_heap_idle_bytes{instance=\"$instance\"}[1m])-avg_over_time(go_memstats_heap_released_bytes{instance=\"$instance\"}[1m])",
     "legendFormat": "Heap Retained"
    }
   ]
  }
 ]
}